<a href="https://colab.research.google.com/github/mnatasha1402/ML-projects/blob/main/MLP_project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train=pd.read_csv("/content/train_data_v2.csv.zip")
test=pd.read_csv("/content/test_data_v2.csv")

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14731 entries, 0 to 14730
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   HomePage                         14578 non-null  float64
 1   HomePage_Duration                14581 non-null  float64
 2   LandingPage                      14578 non-null  float64
 3   LandingPage_Duration             14596 non-null  float64
 4   ProductDescriptionPage           14608 non-null  float64
 5   ProductDescriptionPage_Duration  14564 non-null  float64
 6   GoogleMetric:Bounce Rates        14580 non-null  float64
 7   GoogleMetric:Exit Rates          14602 non-null  float64
 8   GoogleMetric:Page Values         14599 non-null  float64
 9   SeasonalPurchase                 14581 non-null  float64
 10  Month_SeasonalPurchase           14587 non-null  object
 11  OS                               14597 non-null  float64
 12  SearchEngine                     14609 non-null  float64
 13  Zone                             14614 non-null  float64
 14  Type of Traffic                  14588 non-null  float64
 15  CustomerType                     14587 non-null  object
 16  Gender                           14586 non-null  object
 17  Cookies Setting                  14587 non-null  object
 18  Education                        14595 non-null  object
 19  Marital Status                   14601 non-null  object
 20  WeekendPurchase                  14610 non-null  float64
 21  Made_Purchase                    14731 non-null  bool
dtypes: bool(1), float64(15), object(6)
memory usage: 2.4+ MB

In [ ]:
train.shape

(14731, 22)

In [ ]:
train.isnull().sum()

HomePage                           153
HomePage_Duration                  150
LandingPage                        153
LandingPage_Duration               135
ProductDescriptionPage             123
ProductDescriptionPage_Duration    167
GoogleMetric:Bounce Rates          151
GoogleMetric:Exit Rates            129
GoogleMetric:Page Values           132
SeasonalPurchase                   150
Month_SeasonalPurchase             144
OS                                 134
SearchEngine                       122
Zone                               117
Type of Traffic                    143
CustomerType                       144
Gender                             145
Cookies Setting                    144
Education                          136
Marital Status                     130
WeekendPurchase                    121
Made_Purchase                        0
dtype: int64

In [ ]:
test.shape

(6599, 21)

In [ ]:
test.isnull().sum()

HomePage                           51
HomePage_Duration                  55
LandingPage                        56
LandingPage_Duration               75
ProductDescriptionPage             58
ProductDescriptionPage_Duration    63
GoogleMetric:Bounce Rates          66
GoogleMetric:Exit Rates            51
GoogleMetric:Page Values           45
SeasonalPurchase                   45
Month_SeasonalPurchase             58
OS                                 62
SearchEngine                       58
Zone                               47
Type of Traffic                    68
CustomerType                       88
Gender                             64
Cookies Setting                    62
Education                          69
Marital Status                     47
WeekendPurchase                    58
dtype: int64

In [ ]:
train["Month_SeasonalPurchase"]

0        Feb
1        Feb
2        Feb
3        Feb
4        Feb
        ...
14726    Nov
14727    May
14728    Aug
14729    Mar
14730    Mar
Name: Month_SeasonalPurchase, Length: 14731, dtype: object

In [ ]:
train.head()

,HomePage,HomePage_Duration,LandingPage,LandingPage_Duration,ProductDescriptionPage,ProductDescriptionPage_Duration,GoogleMetric:Bounce Rates,GoogleMetric:Exit Rates,GoogleMetric:Page Values,SeasonalPurchase,...,SearchEngine,Zone,Type of Traffic,CustomerType,Gender,Cookies Setting,Education,Marital Status,WeekendPurchase,Made_Purchase
0,0.0,0.0,0.0,0.0,1.0,0.000000,0.20,0.20,0.0,0.0,...,1.0,9.0,3.0,Returning_Visitor,Not Specified,Deny,Not Specified,Other,0.0,False
1,0.0,0.0,0.0,0.0,2.0,2.666667,0.05,0.14,0.0,0.0,...,2.0,2.0,4.0,Returning_Visitor,Female,Deny,Others,Married,0.0,False
2,0.0,0.0,0.0,0.0,10.0,627.500000,0.02,0.05,0.0,0.0,...,3.0,1.0,4.0,Returning_Visitor,Female,ALL,Others,Married,1.0,False
3,0.0,0.0,0.0,0.0,1.0,0.000000,0.20,0.20,0.0,0.4,...,4.0,3.0,3.0,Returning_Visitor,Male,ALL,Diploma,Single,0.0,False
4,1.0,0.0,0.0,0.0,0.0,0.000000,0.20,0.20,0.0,0.0,...,2.0,1.0,5.0,Returning_Visitor,Male,Deny,Diploma,Other,1.0,False

In [ ]:
train_cat=train[["Month_SeasonalPurchase","CustomerType","Education","Gender","Cookies Setting","Marital Status","WeekendPurchase"]]

In [ ]:
train_cat.head()

,Month_SeasonalPurchase,CustomerType,Education,Gender,Cookies Setting,Marital Status,WeekendPurchase
0,Feb,Returning_Visitor,Not Specified,Not Specified,Deny,Other,0.0
1,Feb,Returning_Visitor,Others,Female,Deny,Married,0.0
2,Feb,Returning_Visitor,Others,Female,ALL,Married,1.0
3,Feb,Returning_Visitor,Diploma,Male,ALL,Single,0.0
4,Feb,Returning_Visitor,Diploma,Male,Deny,Other,1.0

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
ct=ColumnTransformer([("oe",OrdinalEncoder(),pd.array(train["Month_SeasonalPurchase"]).reshape(-1,1))])
train_transform=ct.fit_transform(train)

InvalidIndexError: ignored

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
le=OrdinalEncoder()
trans_train_cat=le.fit_transform(train_cat)

In [ ]:
pd.DataFrame(trans_train_cat)

         0    1    2    3    4    5    6
0      2.0  2.0  2.0  2.0  1.0  1.0  0.0
1      2.0  2.0  3.0  0.0  1.0  0.0  0.0
2      2.0  2.0  3.0  0.0  0.0  0.0  1.0
3      2.0  2.0  0.0  1.0  0.0  2.0  0.0
4      2.0  2.0  0.0  1.0  1.0  1.0  1.0
...    ...  ...  ...  ...  ...  ...  ...
14726  7.0  2.0  NaN  0.0  1.0  0.0  0.0
14727  6.0  2.0  0.0  2.0  0.0  0.0  0.0
14728  0.0  2.0  3.0  2.0  2.0  2.0  0.0
14729  5.0  2.0  2.0  2.0  2.0  0.0  0.0
14730  5.0  2.0  0.0  0.0  0.0  1.0  0.0

[14731 rows x 7 columns]

In [ ]:
train.head()

,HomePage,HomePage_Duration,LandingPage,LandingPage_Duration,ProductDescriptionPage,ProductDescriptionPage_Duration,GoogleMetric:Bounce Rates,GoogleMetric:Exit Rates,GoogleMetric:Page Values,SeasonalPurchase,...,SearchEngine,Zone,Type of Traffic,CustomerType,Gender,Cookies Setting,Education,Marital Status,WeekendPurchase,Made_Purchase
0,0.0,0.0,0.0,0.0,1.0,0.000000,0.20,0.20,0.0,0.0,...,1.0,9.0,3.0,Returning_Visitor,Not Specified,Deny,Not Specified,Other,0.0,False
1,0.0,0.0,0.0,0.0,2.0,2.666667,0.05,0.14,0.0,0.0,...,2.0,2.0,4.0,Returning_Visitor,Female,Deny,Others,Married,0.0,False
2,0.0,0.0,0.0,0.0,10.0,627.500000,0.02,0.05,0.0,0.0,...,3.0,1.0,4.0,Returning_Visitor,Female,ALL,Others,Married,1.0,False
3,0.0,0.0,0.0,0.0,1.0,0.000000,0.20,0.20,0.0,0.4,...,4.0,3.0,3.0,Returning_Visitor,Male,ALL,Diploma,Single,0.0,False
4,1.0,0.0,0.0,0.0,0.0,0.000000,0.20,0.20,0.0,0.0,...,2.0,1.0,5.0,Returning_Visitor,Male,Deny,Diploma,Other,1.0,False

In [ ]:
train["Month_SeasonalPurchase"]

0        Feb
1        Feb
2        Feb
3        Feb
4        Feb
        ...
14726    Nov
14727    May
14728    Aug
14729    Mar
14730    Mar
Name: Month_SeasonalPurchase, Length: 14731, dtype: object

In [ ]:
from sklearn.impute import KNNImputer
knni = KNNImputer(n_neighbors=2, weights="uniform")
knni.fit_transform(X)

ValueError: ignored

In [ ]:
y=train["Made_Purchase"]

In [ ]:
y.head()

In [ ]:
y.value_counts()

In [ ]:
df=pd.concat([train,test])

In [ ]:
df.head()

In [ ]:
df.isnull().sum()

In [ ]:
y=df["Made_Purchase"]

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
y.head()

In [ ]:
x.head()

In [ ]:
x.info()

In [ ]:
from sklearn.impute import KNNImputer